name: security-scan

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-scan:
    name: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository history
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0

      - name: Scan committed content
        uses: trufflesecurity/trufflehog@6f3c981e7b77f235fd2702dd74af25fc4b72bf11
        with:
          version: 3.96.0
          extra_args: --no-verification --results=unverified,unknown
